apiVersion: apps/v1
kind: Deployment
metadata:
  name: h2
  namespace: board-game
spec:
  replicas: 1
  selector:
    matchLabels:
      app: h2
  template:
    metadata:
      labels:
        app: h2
    spec:
      containers:
        - name: h2
          image: oscarfonts/h2
          ports:
            - containerPort: 1521
            - containerPort: 81
          env:
            - name: H2_OPTIONS
              value: "-ifNotExists -tcp -tcpAllowOthers -web -webAllowOthers"
          volumeMounts:
            - mountPath: /opt/h2-data
              name: h2-volume
      volumes:
        - name: h2-volume
          persistentVolumeClaim:
            claimName: h2-pvc

