apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: h2-pvc
  namespace: board-game
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ebs-sc
  resources:
    requests:
      storage: 5Gi
