apiVersion: v1
kind: Service
metadata:
  name: h2
  namespace: board-game
spec:
  selector:
    app: h2
  ports:
    - name: tcp
      port: 1521
      targetPort: 1521
    - name: web
      port: 81
      targetPort: 81
  type: ClusterIP

