sonar.projectKey=Bord-game
sonar.projectName=Bord-Game
sonar.sources=.
sonar.java.binaries=target
sonar.java.libraries=target/lib
sonar.host.url=http://localhost:9000
sonar.login=admin
sonar.password=squ_3bf593a71ff3613f33b9b4c32d192e7af9f62771
