sonar.projectKey=Bord-game
sonar.projectName=Bord-Game
sonar.sources=.
sonar.java.binaries=target
sonar.java.libraries=target/lib
sonar.host.url=http://localhost:9000
sonar.login=admin
sonar.password=admin
