apiVersion: apps/v1
kind: Deployment
metadata:
  name: boardgame-app
  namespace: board-game
spec:
  replicas: 4
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: boardgame-app
  template:
    metadata:
      labels:
        app: boardgame-app
    spec:
      containers:
        - name: boardgame-app
          image: ganeshmestry21/bord-game-dev:v1
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:h2:tcp://h2:1521/boardgame-db
            - name: SPRING_DATASOURCE_DRIVER_CLASS_NAME
              value: org.h2.Driver
            - name: SPRING_DATASOURCE_USERNAME
              value: sa
            - name: SPRING_DATASOURCE_PASSWORD
              value: ""
            - name: SPRING_H2_CONSOLE_ENABLED
              value: "true"
            - name: SPRING_H2_CONSOLE_PATH
              value: /h2-console
            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              value: update
            - name: SPRING_SQL_INIT_MODE
              value: always
            - name: SPRING_SQL_INIT_SCHEMA_LOCATIONS
              value: classpath:/schema.sql
          volumeMounts:
            - name: h2-volume
              mountPath: /opt/h2-data
      volumes:
        - name: h2-volume
          persistentVolumeClaim:
            claimName: h2-pvc

