kind: Deployment
metadata:
  name: board-game
  namespace: board-game
apiVersion: apps/v1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: board-game
  template:
    metadata:
      name: board-game
      labels:
        app: board-game
    spec:
      containers:
      automountServiceAccountToken: false
      - name: board-game
        image: ganeshmestry21/bord-game-dev:v1
        ports:
          - containerPort: 8080

        volumeMounts:
            - mountPath: /data           # mount point inside container
              name: board-game-storage
              
        resources:
            requests:
              memory: "256Mi"
              cpu: "250m" 
            limits:
              memory: "512Mi"
              cpu: "500m" 
    volumes:
        - name: board-game-storage
          persistentVolumeClaim:
            claimName: board-game-pvc



