apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: boardgame-app
  namespace: board-game-statfull-app
spec:
  serviceName: boardgame-app
  replicas: 2
  selector:
    matchLabels:
      app: boardgame-app
  template:
    metadata:
      labels:
        app: boardgame-app
    spec:
      containers:
        - name: boardgame-app
          image: ganeshmestry21/bord-game-dev:v1
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "500m"
              memory: "1Gi"
          volumeMounts:
            - name: data
              mountPath: /opt/h2-data
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
