apiVersion: v1
kind: PersistentVolume
metadata:
  name: statfull-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /mnt/data/h2-storage   # Data stored on Minikube VM
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: statfull-pv
  namespace: board-game-statefull-app 
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
