apiVersion: v1
kind: PersistentVolume
metadata:
  name: boardgame-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /mnt/data/h2-storage
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: boardgame-pvc
  namespace: board-game-statfull-app
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
