apiVersion: v1
kind: Service
metadata:
  name: boardgame-app
  namespace: board-game-statfull-app
spec:
  selector:
    app: boardgame-app
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30080
  type: NodePort
