apiVersion: v1
kind: Service
metadata:
  name: board-game-svc
  namespace: board-game        
  labels:
    app: board-game
spec:
  type: ClusterIP
  selector:
    app: board-game
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080