apiVersion: v1
kind: Service
metadata:
  name: boardgame-app
  namespace: board-game-statful-app  
spec:
  selector:
    app: boardgame-app
  ports:
    - port: 80
      targetPort: 8080
  type: NodePort
