apiVersion: apps/v1
kind: Deployment
metadata:
  name: boardgame-app
  namespace: board-game
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: boardgame-app
  template:
    metadata:
      labels:
        app: boardgame-app
    spec:
      containers:
        - name: boardgame-app
          image: ganeshmestry21/bord-game-dev:v1
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "500m"
              memory: "1Gi"
          volumeMounts:
            - name: h2-volume
              mountPath: /opt/h2-data
      volumes:
        - name: h2-volume
          persistentVolumeClaim:
            claimName: h2-pvc

