# ---------------- Deployment ----------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: boardgame-app
  namespace: board-game
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: boardgame-app
  template:
    metadata:
      labels:
        app: boardgame-app
    spec:
      containers:
        - name: boardgame-app
          image: ganeshmestry21/bord-game-dev:v1
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "500m"
              memory: "1Gi"
          volumeMounts:
            - name: h2-volume
              mountPath: /opt/h2-data
      volumes:
        - name: h2-volume
          persistentVolumeClaim:
            claimName: h2-pvc

---
# ---------------- Service ----------------
apiVersion: v1
kind: Service
metadata:
  name: boardgame-app
  namespace: board-game
spec:
  selector:
    app: boardgame-app
  ports:
    - port: 80
      targetPort: 8080
  type: LoadBalancer

---
# ---------------- StorageClass ----------------
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ebs-sc
provisioner: kubernetes.io/aws-ebs
volumeBindingMode: WaitForFirstConsumer
parameters:
  type: gp2

---
# ---------------- PVC ----------------
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: h2-pvc
  namespace: board-game
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: ebs-sc

---
# ---------------- VPA ----------------
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: boardgame-app-vpa
  namespace: board-game
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind:       Deployment
    name:       boardgame-app
  updatePolicy:
    updateMode: "Auto"
  resourcePolicy:
    containerPolicies:
      - containerName: "boardgame-app"
        controlledResources: ["cpu", "memory"]
        minAllowed:
          cpu: "200m"
          memory: "256Mi"
        maxAllowed:
          cpu: "2"
          memory: "4Gi"

